# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://leadershipquickies.com
title: "#eadershipquickies"
email: info@turtletrafo.de
author: Miriam & Markus Schmidberger
description: Every Monday morning, we publish a leadership quickie. This is a short inspiration for your daily leadership work, it will open up your leader mindset, and it reminds you of basic leadership tools and principles.
copyright: 'Copyright &copy; 2023 Turtel Transformation. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: globe
    url: https://turtletrafo.de
  - title: inbox
    url: mailto:info@turtletrafo.de
  - title: linkedin
    url: https://www.linkedin.com/company/turtletrafo
  - title: instagram
    url: https://www.instagram.com/turtletrafo/
  - title: facebook
    url: https://www.facebook.com/turtletrafo
  - title: youtube
    url: https://www.youtube.com/@turtletrafo
  - title: spotify
    url: https://open.spotify.com/show/1hNGs66lvTti53RSPLUyqr
